guests = ["ahmed","yousif","mona","ali","fatima","saeed"]
name= guests[0].title()
print(name+",please come to home.")
name= guests[1].title()
print(name+",please come to home.")
name= guests[2].title()
print(name+",please come to home.")
del(quests[1])
guests.insert(1, "ahmed","yousif")
name=guests[0].title()
print("\n"+name+",please come to home")
name=guests[1].title()
print("\n"+name+",please come to home")
name=guests[2].title()
print("\n"+name+",please come to home")